package stas.lines2019.game.util;

public class ConstantsAchiveEng {

    public static final int NUM_ACHIVEMENTS = 33;

    public static final int TYPE_SCORE        = -7;
    public static final int TYPE_TIME_SINGLE  = -8;
    public static final int TYPE_TIME_OVERALL = -9;
    public static final int TYPE_LINES_SIZE   = -10;
    public static final int TYPE_SCORE_OVERALL  = -11;
    public static final int TYPE_TURNS  = -12;

    public static final String[] achievmentsName = {
            "achivement 1",
            "achivement 2",
            "achivement 3",
            "achivement 4",
            "achivement 5",
            "achivement 6",
            "achivement 7",
            "achivement 8",
            "achivement 9",
            "achivement 10",
            "achivement 11",
            "achivement 12",
            "achivement 13",
            "achivement 14",
            "achivement 15",
            "achivement 16",
            "achivement 17",
            "achivement 18",
            "achivement 19",
            "achivement 20",
            "achivement 21",
            "achivement 22",
            "achivement 23",
            "achivement 24",
            "achivement 25",
            "achivement 26",
            "achivement 27",
            "achivement 28",
            "achivement 29",
            "achivement 30",
            "achivement 31",
            "achivement 32",
            "achivement 33"
    };

    public static final String[] achievementsDescr = {
            "get 100 scores in one game",
            "get 200 scores in one game",
            "get 300 scores in one game",
            "get 400 scores in one game",
            "get 500 scores in one game",
            "get 1500 scores in one game",
            "get 5000 scores in one game",
            "get 1000 scores total",
            "get 2000 scores total",
            "get 5000 scores total",
            "get 10000 scores total",
            "get 20000 scores total",
            "get 50000 scores total",
            "get 100000 scores total",
            "play 10 min in one game",
            "play 20 min in one game",
            "play 30 min in one game",
            "play 40 min in one game",
            "play 60 min in one game",
            "play 1 hours total" ,
            "play 2 hours total" ,
            "play 5 hours total" ,
            "play 10 hours total",
            "play 24 hours total",
            "played 200 turns",
            "played 400 turns",
            "played 600 turns",
            "played 1000 turns",
            "played 2000 turns",
            "get 6 ball line",
            "get 7 ball line",
            "get 8 ball line",
            "get 9 ball line"
    };

    public static final int[] achivementsCriteria = {
            100,
            200,
            300,
            400,
            500,
            1500,
            5000,
            1000,
            2000,
            5000,
            10000,
            20000,
            50000,
            100000,
            10*60,
            20*60,
            30*60,
            40*60,
            60*60,
            1*60*60,
            3*60*60,
            5*60*60,
            15*60*60,
            24*60*60,
            200,
            400,
            600,
            1000,
            2000,
            6,
            7,
            8,
            9
    };

    public static final int[] achivementsType = {
            TYPE_SCORE,
            TYPE_SCORE,
            TYPE_SCORE,
            TYPE_SCORE,
            TYPE_SCORE,
            TYPE_SCORE,
            TYPE_SCORE,
            TYPE_SCORE_OVERALL,
            TYPE_SCORE_OVERALL,
            TYPE_SCORE_OVERALL,
            TYPE_SCORE_OVERALL,
            TYPE_SCORE_OVERALL,
            TYPE_SCORE_OVERALL,
            TYPE_SCORE_OVERALL,
            TYPE_TIME_SINGLE,
            TYPE_TIME_SINGLE,
            TYPE_TIME_SINGLE,
            TYPE_TIME_SINGLE,
            TYPE_TIME_SINGLE,
            TYPE_TIME_OVERALL,
            TYPE_TIME_OVERALL,
            TYPE_TIME_OVERALL,
            TYPE_TIME_OVERALL,
            TYPE_TIME_OVERALL,
            TYPE_TURNS,
            TYPE_TURNS,
            TYPE_TURNS,
            TYPE_TURNS,
            TYPE_TURNS,
            TYPE_LINES_SIZE,
            TYPE_LINES_SIZE,
            TYPE_LINES_SIZE,
            TYPE_LINES_SIZE,
    };

    public static final int[] achivementsCost = {
            20,
            50,
            100,
            200,
            500,
            1500,
            5000,
            1000,
            2000,
            5000,
            10000,
            20000,
            50000,
            100000,
            5*60,
            10*60,
            20*60,
            40*60,
            60*60,
            1*60*60,
            2*60*60,
            5*60*60,
            10*60*60,
            24*60*60,
            20,
            40,
            100,
            200,
            500,
            6,
            7,
            8,
            9
    };

    public ConstantsAchiveEng() {
//        achievmentsName = new String[NUM_ACHIVEMENTS];
    }



}
