package stas.lines2019.game.util;



public class ConstantsAchiveEng {

    public static final int NUM_ACHIVEMENTS = 41;

    public static final int TYPE_SCORE        = -7;
    public static final int TYPE_TIME_SINGLE  = -8;
    public static final int TYPE_TIME_OVERALL = -9;
    public static final int TYPE_LINES_SIZE   = -10;
    public static final int TYPE_SCORE_OVERALL  = -11;
    public static final int TYPE_TURNS  = -12;
    public static final int TYPE_SURVIVE = -13;

    public static final String[] achievmentsName = {
            "achivement 1",
            "achivement 2",
            "achivement 3",
            "achivement 4",
            "achivement 5",
            "achivement 6",
            "achivement 7",
            "achivement 8",
            "achivement 9",
            "achivement 10",
            "achivement 11",
            "achivement 12",
            "achivement 13",
            "achivement 14",
            "achivement 15",
            "achivement 16",
            "achivement 17",
            "achivement 18",
            "achivement 19",
            "achivement 20",
            "achivement 21",
            "achivement 22",
            "achivement 23",
            "achivement 24",
            "achivement 25",
            "achivement 26",
            "achivement 27",
            "achivement 28",
            "achivement 29",
            "achivement 30",
            "achivement 31",
            "achivement 32",
            "achivement 33",
            "achivement 34",
            "achivement 35",
            "achivement 36",
            "achivement 37",
            "achivement 38",
            "achivement 39",
            "achivement 40",
            "achivement 41",
    };

    public static final String[] achievementsDescr = {
            Assets.instance.bundle.get("get")+ " 200 + " + Assets.instance.bundle.get("scoreInOneTurn"),
            Assets.instance.bundle.get("get")+ " 500 + " + Assets.instance.bundle.get("scoreInOneTurn"),
            Assets.instance.bundle.get("get")+ " 1000 + " + Assets.instance.bundle.get("scoreInOneTurn"),
            Assets.instance.bundle.get("get")+ " 2000 + " + Assets.instance.bundle.get("scoreInOneTurn"),
            Assets.instance.bundle.get("get")+ " 5000 + " + Assets.instance.bundle.get("scoreInOneTurn"),
            Assets.instance.bundle.get("get")+ " 15000 + " + Assets.instance.bundle.get("scoreInOneTurn"),
            Assets.instance.bundle.get("get")+ " 50000 + " + Assets.instance.bundle.get("scoreInOneTurn"),
            Assets.instance.bundle.get("get")+ " 1000 + " + Assets.instance.bundle.get("scoresTotal"),
            Assets.instance.bundle.get("get")+ " 2000 + " + Assets.instance.bundle.get("scoresTotal"),
            Assets.instance.bundle.get("get")+ " 5000 + " + Assets.instance.bundle.get("scoresTotal"),
            Assets.instance.bundle.get("get")+ " 10000 + " + Assets.instance.bundle.get("scoresTotal"),
            Assets.instance.bundle.get("get")+ " 20000 + " + Assets.instance.bundle.get("scoresTotal"),
            Assets.instance.bundle.get("get")+ " 50000 + " + Assets.instance.bundle.get("scoresTotal"),
            Assets.instance.bundle.get("get")+ " 150000 + " + Assets.instance.bundle.get("scoresTotal"),
            Assets.instance.bundle.get("play") + " 10 " + Assets.instance.bundle.get("minInOne"),
            Assets.instance.bundle.get("play") + " 20 " + Assets.instance.bundle.get("minInOne"),
            Assets.instance.bundle.get("play") + " 40 " + Assets.instance.bundle.get("minInOne"),
            Assets.instance.bundle.get("play") + " 60 " + Assets.instance.bundle.get("minInOne"),
            Assets.instance.bundle.get("play") + " 90 " + Assets.instance.bundle.get("minInOne"),
            Assets.instance.bundle.get("play") + " 1 " +  Assets.instance.bundle.get("hoursTot"),
            Assets.instance.bundle.get("play") + " 2 " +  Assets.instance.bundle.get("hoursTot") ,
            Assets.instance.bundle.get("play") + " 5 " +  Assets.instance.bundle.get("hoursTot"),
            Assets.instance.bundle.get("play") + " 10 " +  Assets.instance.bundle.get("hoursTot"),
            Assets.instance.bundle.get("play") + " 24 " +  Assets.instance.bundle.get("hoursTot"),
            Assets.instance.bundle.get("play") +" 200 " + Assets.instance.bundle.get("turns"),
            Assets.instance.bundle.get("play") +" 400 " + Assets.instance.bundle.get("turns"),
            Assets.instance.bundle.get("play") +" 600 " + Assets.instance.bundle.get("turns"),
            Assets.instance.bundle.get("play") +" 1000 " + Assets.instance.bundle.get("turns"),
            Assets.instance.bundle.get("play") +" 2000 " + Assets.instance.bundle.get("turns"),
            Assets.instance.bundle.get("get")+ " 6 " +Assets.instance.bundle.get("BalLine"),
            Assets.instance.bundle.get("get")+ " 7 " +Assets.instance.bundle.get("BalLine"),
            Assets.instance.bundle.get("get")+ " 8 " +Assets.instance.bundle.get("BalLine"),
            Assets.instance.bundle.get("get")+ " 9 " +Assets.instance.bundle.get("BalLine"),

            Assets.instance.bundle.get("achSurvEasy"),
            Assets.instance.bundle.get("achSurvNorm"),
            Assets.instance.bundle.get("achSurvHard"),
            Assets.instance.bundle.get("achSurvNightmare"),
            Assets.instance.bundle.get("achSurvendl") + " 10",
            Assets.instance.bundle.get("achSurvendl") + " 20",
            Assets.instance.bundle.get("achSurvendl") + " 40",
            Assets.instance.bundle.get("achSurvendl") + " 60"
    };

    public static final int[] achivementsCriteria = {
            200,
            500,
            1000,
            2000,
            5000,
            15000,
            50000,
            1000,
            2000,
            5000,
            10000,
            20000,
            50000,
            100000,
            10*60,
            20*60,
            40*60,
            60*60,
            90*60,
            1*60*60,
            3*60*60,
            5*60*60,
            15*60*60,
            24*60*60,
            200,
            400,
            600,
            1000,
            2000,
            6,
            7,
            8,
            9,

            Constants.DIFFICULT_EASY,
            Constants.DIFFICULT_NORMAL,
            Constants.DIFFICULT_HARD,
            Constants.DIFFICULT_NIGHTMARE,
            Constants.DIFFICULT_ENDLESS,
            Constants.DIFFICULT_ENDLESS,
            Constants.DIFFICULT_ENDLESS,
            Constants.DIFFICULT_ENDLESS,
    };

    public static final int[] achivementsType = {
            TYPE_SCORE,
            TYPE_SCORE,
            TYPE_SCORE,
            TYPE_SCORE,
            TYPE_SCORE,
            TYPE_SCORE,
            TYPE_SCORE,
            TYPE_SCORE_OVERALL,
            TYPE_SCORE_OVERALL,
            TYPE_SCORE_OVERALL,
            TYPE_SCORE_OVERALL,
            TYPE_SCORE_OVERALL,
            TYPE_SCORE_OVERALL,
            TYPE_SCORE_OVERALL,
            TYPE_TIME_SINGLE,
            TYPE_TIME_SINGLE,
            TYPE_TIME_SINGLE,
            TYPE_TIME_SINGLE,
            TYPE_TIME_SINGLE,
            TYPE_TIME_OVERALL,
            TYPE_TIME_OVERALL,
            TYPE_TIME_OVERALL,
            TYPE_TIME_OVERALL,
            TYPE_TIME_OVERALL,
            TYPE_TURNS,
            TYPE_TURNS,
            TYPE_TURNS,
            TYPE_TURNS,
            TYPE_TURNS,
            TYPE_LINES_SIZE,
            TYPE_LINES_SIZE,
            TYPE_LINES_SIZE,
            TYPE_LINES_SIZE,

            TYPE_SURVIVE,
            TYPE_SURVIVE,
            TYPE_SURVIVE,
            TYPE_SURVIVE,
            TYPE_SURVIVE,
            TYPE_SURVIVE,
            TYPE_SURVIVE,
            TYPE_SURVIVE
    };

    public static final int[] achivementsCost = {
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,

            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
    };

    public ConstantsAchiveEng() {
//        achievmentsName = new String[NUM_ACHIVEMENTS];
    }



}
